### ISSUE TITLE
Allow for deployment to local packages other than '$tmp'

### ISSUE THREAD

**Issue by TheGreenToaster** [nrdev88/nwabap-ui5uploader#11]
Packages starting with '$' or 'T' can be local and not require a transport.

https://answers.sap.com/questions/9025981/a-question-about-creating-packages-as-local-object.html

I would like to change the validation to check for these conditions instead of if the package name is '$TMP'. I will submit a PR if thats alright.

**Comment by nrdev88** [comment]
Fixed in #16
