### ISSUE TITLE
[Feature Request] ICF node generation

### ISSUE THREAD

**Issue by doradsoft** [nrdev88/nwabap-ui5uploader#15]
If the application is being created for the first time, it would be useful if an [ICF node](https://help.sap.com/erp_hcm_ias2_2014_03/helpdata/en/cb/c2cc51e637c00ce10000000a445394/content.htm?no_cache=true) could be generated.

**Comment by nrdev88** [comment]
A SICF entry is automatically created when creating the BSP app. Could you explain more detailed what you need?

**Comment by doradsoft** [comment]
Thanks for your response. I am out of office, and will attach a reproduce the next days.

**Comment by nrdev88** [comment]
Closed due to inactivity
