### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by pfefferf** [nrdev88/nwabap-ui5uploader#2]
By using code of https://www.npmjs.com/package/grunt-nwabap-ui5uploader in your project w/o mentioning it, you are violating the Apache 2.0 license. Please remove the code or fulfill the license requirements.

**Comment by nrdev88** [comment]
Hi pfefferf, I'm sorry for only leaving it only in the readme. 

> "Based on original gulp and grunt plugins
> This module is based on the original gulp and grunt plugins. Though I didn't like the need of gulp or grunt in my projects purely for CI/CD." 

Could you assist on how you want it to be (should be)? I really don't wanna take the credits, it's just a quick private solution I shared :-)

**Comment by pfefferf** [comment]
It is all described in the Apache License file under point 4: https://github.com/pfefferf/grunt-nwabap-ui5uploader/blob/master/LICENSE-Apache-2.0
