### ISSUE TITLE
Deployment of SAP UI5 Adaptation Projects

### ISSUE THREAD

**Issue by piejanssens** [nrdev88/nwabap-ui5uploader#20]
SAP plans to support creating _Adaptation Projects_ via VS Code at some point in 2021.
Meanwhile, one could use BAS to scaffold the project and export it, then continue in VS Code.
Deployment is done via LREP, not ADT in case of adaptation projects.

https://blogs.sap.com/2020/07/15/adaptation-project-your-one-stop-tool-for-extending-sapui5-applications/

**Comment by nrdev88** [comment]
Could you please elaborate what is the exact issue/request you are doing?
