### ISSUE TITLE
No way to upload files which start from "." (dot)

### ISSUE THREAD

**Issue by tomasz-sobkowiak** [nrdev88/nwabap-ui5uploader#21]
Hi all,

I have just noticed that files which start from "." (i.e. .library) are not being uploaded to SAP.
In the **upload.js** file there is the **glob.sync** function, which takes as parameters only the **cwd** from nwabap-ui5uploader options:
![image](https://user-images.githubusercontent.com/68218263/115006475-37565b00-9ea9-11eb-9cec-b354a3a76f26.png)
Inside the **glob.sync** (fast-glob -> which is used by nwabap-ui5uploader) the **dot** option is set by default as **false**:
![image](https://user-images.githubusercontent.com/68218263/115007238-104c5900-9eaa-11eb-8741-1b98d942fd48.png)

In the mean-time I checked the **grunt-nwabap-ui5uploader** and the **dot** option is set to TRUE by default:
![image](https://user-images.githubusercontent.com/68218263/115007462-4d185000-9eaa-11eb-976d-89d37fdc4f75.png)

Would it be possible to add additional option in the **nwabap-ui5uploader** to pass through the **dot** parameter to the **glob.sync** (fast-glob)?

Best regards,
Tomasz

**Comment by nrdev88** [comment]
Merged your PR #22
