### ISSUE TITLE
git_diff_commit not working propperly

### ISSUE THREAD

**Issue by senenpalanca** [nrdev88/nwabap-ui5uploader#24]
When I don't use this option everything is OK and I am able to upload to my gateway, but when I use it, it detects changed files but not uploads them. I get this message but never arribes to upload. 
![image](https://user-images.githubusercontent.com/19634907/119783874-f309a200-becd-11eb-9d91-fa75c0b09bd1.png)

this is my config: 
![image](https://user-images.githubusercontent.com/19634907/119784322-5f84a100-bece-11eb-93b3-671f433cf0b1.png)

And this is my uploading command: 
" ui5 build -a --clean-dest --include-task=generateManifestBundle generateCachebusterInfo && rimraf archive.zip && npx nwabap upload"

**Comment by dehero** [comment]
As I see, you do build your application before deploying it. The build goes into `./dist` folder by default, but in your config there is `./webapp` base folder. This is common to add `./dist` to `.gitignore`, so `git_diff_commit` becomes unnecessary.

**Comment by nrdev88** [comment]
Could you please elaborate on @dehero's reply and tell us your exact findings.

**Comment by nrdev88** [comment]
No reply.
