### ISSUE TITLE
Uploading takes a lot of time

### ISSUE THREAD

**Issue by zayidu** [nrdev88/nwabap-ui5uploader#26]
I am running this script from my mac terminal, and my mac is also connected to my organization network. Still it takes a lot of time to upload the files to the abap repo.

Any fix?

**Comment by nrdev88** [comment]
Are you sure this isn't a network issue? For reference: If you have +-25 files with a total of +-4MB it takes approx. 20s. Each file is a seperate request, this can't be different with the ADT services which this tool uses.
