### ISSUE TITLE
Deployment - if SSO enabled with ABAP Repo.

### ISSUE THREAD

**Issue by mgggkn** [nrdev88/nwabap-ui5uploader#27]
Hi,
if my user account is enabled with SSO in ABAP Repo, how can i make the deployment successful? I supplied "conn_user" and removed "conn_password", I was getting an error says "Define both a username and password." Any help? Does this module support only non-SSO scenario?

Thanks
Gokul.

**Comment by nrdev88** [comment]
SSO is not supported by this plugin unfortunately! Please check if this is possible and do a merge request, thank you!
