### ISSUE TITLE
Transmission breaks often with different Errors

### ISSUE THREAD

**Issue by ChristianSchaub1** [nrdev88/nwabap-ui5uploader#31]
Hi Guys, 

following Issues occur often when i try to upload my ui5 App:

Very often:
Request-Url: ..../sap/bc/adt/filestore/ui5-bsp/objects/....
Request-Method: put
Error: socket hang up
Details:
undefined

Sometimes:
The other Error is an csrf Failure, i don't have a example at the moment.
Something like csrf token verification failed

We got an Azure Pipeline running this tasks, there the "socket hung up" Issue never occured, only the csrf failure sometimes.

At the moment we can't use the Azure Pipeline, so we have to upload form our local Devices and the Transmission breaks are annoying.

Can you give us an advice what we maybe are doing wrong or take this Issue into your "to-do List".

Greetz
Christian

**Comment by ChristianSchaub1** [comment]
Here is the csrf Error, occured just at the moment:

This time when posting the new index, other times when i upload any other file.

[11:13:58] [FAILED] Calculating application index.
Error! Request-Url: ..../sap/bc/adt/filestore/ui5-bsp/appindex/....
Request-Method: post
Error: got 403 response
Details:
CSRF-Token-Validierung ist fehlgeschlagen

**Comment by nrdev88** [comment]
It seems ADT services are either not enabled, or you do not have sufficient authorization for using ADT services. Please check documentation for which role you need to have in order to use ADT services.
